import { Article, Location } from '../types';

export const MOCK_ARTICLES: Article[] = [
  {
    id: '10',
    header: 'Major Water Pipe Burst on Herzl Street — Road Closed to Traffic',
    category: 'Roads',
    summary: 'A main water pipe burst at the corner of Herzl and Jabotinsky, causing significant flooding. Road is blocked and repair teams are on site.',
    content: '',
    author: 'Zekan Local',
    date: new Date(Date.now() - 15 * 60000).toISOString(),
    created_at: new Date(Date.now() - 20 * 60000).toISOString(),
    last_updated: new Date(Date.now() - 15 * 60000).toISOString(),
    credibility_score: null,
    external_sources: null,
    area_exterior: null,
    imageUrl: require('../assets/pipe_burst.jpg'),
    region: 'תל-אביב',
    is_urgent: true,
    languages: {
      en: {
        title: 'Major Water Pipe Burst on Herzl Street — Road Closed to Traffic',
        summary: 'A main water pipe burst at the corner of Herzl and Jabotinsky, causing significant flooding. Repair teams are on site; fix expected by evening.',
        body: 'A main water pipe burst on Herzl Street at the corner of Jabotinsky, causing significant flooding. While neighbourhood WhatsApp groups are still trading rumours about the source of the noise, those in the area already received a targeted push alert and bypassed the traffic jam in time. The system ensures only residents for whom the event is relevant receive an urgent notification — unlike the endless noise on Facebook. Repair teams are on site; the fix is expected to be completed by evening.',
        key_facts: [
          'Pipe burst at Herzl / Jabotinsky intersection',
          'Road closed to traffic',
          'Significant flooding reported',
          'Repairs expected by evening',
        ],
      },
      he: {
        title: 'פיצוץ צינור מים מרכזי ברחוב הרצל: הרחוב חסום לתנועה',
        summary: 'צינור מים ראשי התפוצץ ברחוב הרצל פינת ז\'בוטינסקי וגרם להצפה משמעותית. הצוותים בשטח, התיקון צפוי להסתיים לקראת ערב.',
        body: 'צינור מים ראשי התפוצץ ברחוב הרצל פינת ז\'בוטינסקי וגרם להצפה משמעותית. בעוד שבקבוצות הווטסאפ השכונתיות עדיין מחליפים שמועות על מקור הרעש, מי שנמצא באזור כבר קיבל התרעת Push ממוקדת ועקף את הפקק בזמן. המערכת מוודאת שרק מי שהאירוע רלוונטי אליו יקבל התראה דחופה, בניגוד לרעש הבלתי פוסק והחופר בפייסבוק. הצוותים בשטח, התיקון צפוי להסתיים לקראת ערב.',
        key_facts: [
          'הפיצוץ בצומת הרצל / ז\'בוטינסקי',
          'הרחוב חסום לתנועה',
          'הצפה משמעותית בשטח',
          'התיקון צפוי לקראת ערב',
        ],
      },
    },
  },
  {
    id: '11',
    header: 'New Neighbourhood Pizzeria "Pizza De Luca" Opens on Bialik Street',
    category: 'Economy',
    summary: 'Pizza De Luca opened its doors on Bialik Street with authentic Neapolitan pizza from a wood-fired oven. Open until midnight today.',
    content: '',
    author: 'Zekan Local',
    date: new Date(Date.now() - 60 * 60000).toISOString(),
    created_at: new Date(Date.now() - 70 * 60000).toISOString(),
    last_updated: new Date(Date.now() - 60 * 60000).toISOString(),
    imageUrl: null,
    credibility_score: null,
    external_sources: null,
    area_exterior: null,
    region: 'תל אביב',
    languages: {
      en: {
        title: 'New Neighbourhood Pizzeria "Pizza De Luca" Opens on Bialik Street',
        summary: 'Pizza De Luca opened its doors on Bialik Street with authentic Neapolitan pizza from a wood-fired oven. Open until midnight today.',
        body: '"Pizza De Luca" opened on Bialik Street with authentic Neapolitan pizza from a wood-fired oven. On social media it is hard for businesses to reach residents without paying a fortune for promotion or waiting days for a Facebook group admin to approve a post. Here, information appears instantly and is open to everyone — any resident or business owner can join immediately, read and post without filters or gatekeepers. The venue is open until midnight tonight.',
        key_facts: [
          'Authentic Neapolitan pizza from a wood-fired oven',
          'Located on Bialik Street',
          'Open today until midnight',
        ],
      },
      he: {
        title: 'הפיצרייה השכונתית החדשה שמשגעת את המרכז נפתחה להרצה',
        summary: '"פיצה דה לוקה" פתחה את שעריה ברחוב ביאליק עם פיצה נפוליטנית אמיתית מטאבון עצים. המקום פתוח היום עד חצות.',
        body: '"פיצה דה לוקה" פתחה את שעריה ברחוב ביאליק עם פיצה נפוליטנית אמיתית מטאבון עצים. ברשתות החברתיות קשה לעסקים להגיע לתושבים בלי לשלם הון על קידום או לחכות ימים שאיזה מנהל קבוצה בפייסבוק יאשר את הפוסט. כאן המידע עולה במידיות ופתוח לכולם. כל תושב ובעל עסק יכול להצטרף ברגע, לקרוא ולעדכן בלי פילטרים ובלי "שומרים בשער". המקום פתוח היום עד חצות.',
        key_facts: [
          'פיצה נפוליטנית מטאבון עצים',
          'ממוקם ברחוב ביאליק',
          'פתוח היום עד חצות',
        ],
      },
    },
  },
  {
    id: '13',
    header: 'Suspicious Object Found Near Playground on KKL Street — EOD En Route',
    category: 'Defence and Security',
    summary: 'A suspicious object was discovered near the playground on KKL Street. Security forces have closed the street and are awaiting a bomb disposal unit.',
    content: '',
    author: 'Zekan Local',
    date: new Date(Date.now() - 5 * 60000).toISOString(),
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
    last_updated: new Date(Date.now() - 5 * 60000).toISOString(),
    imageUrl: null,
    credibility_score: null,
    external_sources: null,
    area_exterior: null,
    region: 'תל-אביב',
    is_urgent: true,
    languages: {
      en: {
        title: 'Suspicious Object Found Near Playground on KKL Street — EOD En Route',
        summary: 'A suspicious object was discovered near the playground on KKL Street. Security forces have closed the street and are awaiting a bomb disposal unit.',
        body: 'A suspicious object was discovered a short time ago near the playground on KKL Street. Security forces have sealed off the road and are awaiting the bomb disposal unit. Events like this typically generate hysteria and baseless rumours in neighbourhood WhatsApp groups. Here you will only get the facts as they are on the ground. An urgent alert was sent only to residents of the immediately adjacent streets to maintain awareness, without creating unnecessary panic in the rest of the city.',
        key_facts: [
          'Suspicious object near playground on KKL Street',
          'Street sealed off by security forces',
          'EOD unit en route',
          'Alert sent only to adjacent street residents',
        ],
      },
      he: {
        title: 'חפץ חשוד אותר בגן המשחקים ברחוב קק"ל; חבלן בדרך',
        summary: 'חפץ חשוד התגלה לפני זמן קצר סמוך לגן השעשועים ברחוב קק"ל. כוחות ביטחון חסמו את הרחוב וממתינים לחבלן.',
        body: 'חפץ חשוד התגלה לפני זמן קצר סמוך לגן השעשועים. כוחות ביטחון חסמו את הרחוב וממתינים לחבלן. אירועים כאלה מייצרים בדרך כלל היסטריה ושמועות חסרות בסיס בקבוצות הווטסאפ השכונתיות. פה תקבלו רק את העובדות כפי שהן בשטח. התרעה דחופה נשלחה לתושבי הרחובות הסמוכים בלבד כדי לשמור על ערנות, מבלי לייצר פאניקה מיותרת בשאר חלקי העיר.',
        key_facts: [
          'חפץ חשוד סמוך לגן השעשועים ברחוב קק"ל',
          'הרחוב חסום על ידי כוחות ביטחון',
          'חבלן בדרך',
          'התרעה נשלחה לרחובות הסמוכים בלבד',
        ],
      },
    },
  },
  {
    id: '14',
    header: 'Fed Up with the WhatsApp Noise? Meet the New Way to Stay Informed',
    category: 'Technology',
    summary: 'Zekan app cuts through the flood of city Facebook and WhatsApp groups, delivering a clean, location-based feed with push alerts only for truly urgent events.',
    content: '',
    author: 'Zekan Editorial',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 1.1 * 86400000).toISOString(),
    last_updated: new Date(Date.now() - 1 * 86400000).toISOString(),
    imageUrl: null,
    credibility_score: null,
    external_sources: null,
    area_exterior: null,
    region: 'ידיעות',
    languages: {
      en: {
        title: 'Fed Up with the WhatsApp Noise? Meet the New Way to Stay Informed',
        summary: 'Zekan app cuts through the flood of city Facebook and WhatsApp groups, delivering a clean, location-based feed with push alerts only for truly urgent events.',
        body: 'We are all flooded with hundreds of messages a day in municipal Facebook and WhatsApp groups, and miss what actually matters. The Zekan app brings order: it lets anyone join instantly — no special approval needed from group admins. The system sends push notifications only for urgent events (road closures, emergencies, or critical updates), and displays a clean, location-based feed that shows you exactly what is happening right now under your building.',
        key_facts: [
          'Join instantly — no group admin approval required',
          'Push alerts only for truly urgent local events',
          'Clean location-based feed, no algorithms',
          'Available now',
        ],
      },
      he: {
        title: 'נמאס מהחפירות בווטסאפ? הכירו את הדרך החדשה להתעדכן',
        summary: 'אפליקציית זה-כאן(Zekan) עושה סדר: פיד נקי מבוסס מיקום, התראות קופצות רק על אירועים דחופים, וכניסה מיידית ללא אישורים.',
        body: 'כולנו מוצפים במאות הודעות ביום בקבוצות פייסבוק וווטסאפ עירוניות, ומפספסים את מה שחשוב באמת. אפליקציית זה-כאן(Zekan) עושה סדר: היא מאפשרת לכל אחד להצטרף באופן מיידי – ללא צורך באישורים מיוחדים ממנהלי קבוצות. המערכת שולחת מקפיצה התראות אך ורק על אירועים דחופים (חסימות, חירום או עדכונים קריטיים), ומציגה פיד נקי, מבוסס מיקום, שמראה לכם בדיוק מה קורה עכשיו מתחת לבית. ללא הרשמה וללא פרסומות',
        key_facts: [
          'הצטרפות מיידית ללא אישור ממנהל קבוצה',
          'התראות קופצות רק על אירועים דחופים ומקומיים',
          'פיד נקי מבוסס מיקום, ללא אלגוריתמים',
          'זמין עכשיו',
        ],
      },
    },
  },
];

export const MOCK_LOCATIONS: Location[] = [
  { id: 'loc1', name: 'Tel Aviv', level: 'city', parent: null, polygon: null },
  { id: 'loc2', name: 'Jerusalem', level: 'city', parent: null, polygon: null },
  { id: 'loc3', name: 'Gaza', level: 'region', parent: null, polygon: null },
  { id: 'loc4', name: 'Southern Lebanon', level: 'region', parent: null, polygon: null },
  { id: 'loc5', name: 'West Bank', level: 'region', parent: null, polygon: null },
];
