FROM nginx:alpine
COPY landing/index.html   /usr/share/nginx/html/index.html
COPY landing/privacy.html /usr/share/nginx/html/privacy.html
COPY landing/og-image.svg /usr/share/nginx/html/og-image.svg
COPY landing/robots.txt   /usr/share/nginx/html/robots.txt
COPY landing/nginx.conf   /etc/nginx/templates/default.conf.template
