FROM nginx:alpine
COPY landing/index.html /usr/share/nginx/html/index.html
COPY landing/privacy.html /usr/share/nginx/html/privacy.html
COPY landing/nginx.conf /etc/nginx/templates/default.conf.template
